spring.application.name=api-management-service

server.port=8081

info.app.name=API Management Service
info.app.description=Management Service for users, routes and gateway policies.

spring.datasource.url=jdbc:mysql://localhost:3306/gatekeeper_management
spring.datasource.username=root
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
